### ISSUE TITLE
opinions on column width

### ISSUE THREAD

**Issue by tkphd** [guyer/mpilogging#6]
Although the GitHub editor inteface is [127 characters wide](https://github.com/guyer/mpilogging/blob/df9719cb61fe3edd3b3e633a3a49562fc63b2b42/.github/workflows/python-package.yml#L39), the GitHub diff interface is only 80 characters wide. Wrapping at 80 makes PR code reviews less choppy.

**Comment by guyer** [comment]
I guess. This stuff all comes in the default GH Action workflow.

**Comment by tkphd** [comment]
Well, the default GH Action workflow is dumb.
